apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-data-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-dev-account-cfg
data:
  geth-dev-account-passwd.txt: |
    testPassword123

---
apiVersion: v1
kind: Pod
metadata:
  name: geth-node
  labels:
    app: geth
spec:
  containers:
    - name: geth
      image: ethereum/client-go:alltools-stable
      command: ["geth"]
      args: [
          "--dev",
          "--http",
          "--http.vhosts=*",
          "--http.addr",
          "0.0.0.0",
          "--http.api",
          "eth,net,web3",
          "--datadir",
          "/.ethereum",
          "--password",
          "geth-dev-account-passwd.txt",
          "--http.corsdomain",
          "*",
        ] # Allow CORS for Remix IDE testing
      resources:
        limits:
          memory: "10Gi"
          cpu: "500m"
      ports:
        - containerPort: 8545
          name: geth
          protocol: TCP
      volumeMounts:
        - name: geth-data
          mountPath: /.ethereum
        - name: dev-account-cfg
          mountPath: /geth-dev-account-passwd.txt
          subPath: geth-dev-account-passwd.txt
  volumes:
    - name: geth-data
      persistentVolumeClaim:
        claimName: geth-data-pvc
    - name: dev-account-cfg
      configMap:
        name: geth-dev-account-cfg

---
apiVersion: v1
kind: Service
metadata:
  name: geth-node
  labels:
    app: geth
spec:
  type: ClusterIP
  ports:
    - name: geth
      port: 8545
      targetPort: 8545
      protocol: TCP
  selector:
    app: geth
