apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs-api
  template:
    metadata:
      labels:
        app: ipfs-api
    spec:
      containers:
        - name: ipfs-api
          image: gabilb/ipfs-api:v1.0.1
          imagePullPolicy: Always
          env:
            - name: IPFS_NODE_IP
              value: "ipfs-node"
            - name: IPFS_NODE_PORT
              value: "5001"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-api
  labels:
    app: ipfs-api
spec:
  selector:
    app: ipfs-api
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
