apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-contract-master-key
data:
# REPLACE THIS WITH A VALID MASTER KEY FROM THE GETH NODE
  master-key.json: |
    {
      "address": "689a78527274e0e76fa6c21eb5eb0acb5c7d052e",
      "crypto": {
        "cipher": "aes-128-ctr",
        "ciphertext": "0c3c32fad910311d8f19b4e3afed2b663303e5a6c02ca1bcb97e0cfd50a90953",
        "cipherparams": {
          "iv": "ec1ce686c2b2fccc4812fde5a8da93d2"
        },
        "kdf": "scrypt",
        "kdfparams": {
          "dklen": 32,
          "n": 4096,
          "p": 6,
          "r": 8,
          "salt": "8ee1e3da56e975667ba8411d875592fd698ea3a97c93e1d521164d11c9d0e4ef"
        },
        "mac": "e6622362cff0790b6d64951e2c1aab0865793149369b122ead447d92bbb50d4d"
      },
      "id": "d4eac015-5bec-4a0d-807d-bbfd820a6040",
      "version": 3
    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-contract-api
spec:
  selector:
    matchLabels:
      app: smart-contract-api
  template:
    metadata:
      labels:
        app: smart-contract-api
    spec:
      containers:
        - name: smart-contract-api
          image: gabilb/smart-contract-api:v1.0.0
          imagePullPolicy: Always
          env:
            - name: IPFS_API_HOST
              value: "ipfs-api"
            - name: IPFS_API_PORT
              value: "8080"
            - name: DB_HOST
              value: "postgres-rw"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "educhain"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-user-creds
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-user-creds
            - name: NET_URL
              value: "http://geth-node:8545"
            - name: JWT_SIGNING_KEY
              value: "superSecretKey"
            - name: MASTER_KEY
              value: "/master-key.json"
            - name: MASTER_KEY_PASSWD
              value: "testPassword123"
          volumeMounts:
            - name: smart-contract-master-key
              mountPath: /master-key.json
              subPath: master-key.json
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              port: 8081
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: smart-contract-master-key
          configMap:
            name: smart-contract-master-key

---
apiVersion: v1
kind: Service
metadata:
  name: smart-contract-api
  labels:
    app: smart-contract-api
spec:
  selector:
    app: smart-contract-api
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30081
