apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-contract-master-key
data:
# REPLACE THIS WITH A VALID MASTER KEY FROM THE GETH NODE
  master-key.json: |
    {"address":"71562b71999873db5b286df957af199ec94617f7","crypto":{"cipher":"aes-128-ctr","ciphertext":"0d190456613a9bd9656caf9dcc9fe73f6de6514bbb3dd181989d6b41c026eedb","cipherparams":{"iv":"851a1686fa023e86f64ccf199ac49a28"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":4096,"p":6,"r":8,"salt":"8db8f28c67bd92a4092ccce1ff31c56a838a051a06c94724364414acef69a02c"},"mac":"18c60f5607d1d311b54aa4dd7310d1f04f5dd08ab6f5df458411f0e7c5f6f721"},"id":"545bd094-bfc4-4866-8f16-5ffbf3cecaf4","version":3}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-contract-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-contract-api
  template:
    metadata:
      labels:
        app: smart-contract-api
    spec:
      containers:
        - name: smart-contract-api
          image: gabilb/smart-contract-api:v1.0.9
          imagePullPolicy: Always
          env:
            - name: IPFS_API_HOST
              value: "ipfs-api"
            - name: IPFS_API_PORT
              value: "8080"
            - name: DB_HOST
              value: "postgres-rw"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "educhain"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-user-creds
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-user-creds
            - name: NET_URL
              value: "http://geth-node:8545"
            - name: JWT_SIGNING_KEY
              value: "superSecretKey"
            - name: MASTER_KEY
              value: "/master-key.json"
            - name: MASTER_KEY_PASSWD
              value: "testPassword123"
          volumeMounts:
            - name: smart-contract-master-key
              mountPath: /master-key.json
              subPath: master-key.json
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              port: 8081
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: smart-contract-master-key
          configMap:
            name: smart-contract-master-key

---
apiVersion: v1
kind: Service
metadata:
  name: smart-contract-api
  labels:
    app: smart-contract-api
spec:
  selector:
    app: smart-contract-api
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30081
