apiVersion: v1
kind: ConfigMap
metadata:
  name: hardhat-cfg-basic
data:
  hardhat.config.js: |
    /** @type import('hardhat/config').HardhatUserConfig */
    module.exports = {
        solidity: "0.8.29",
        networks: {
            hardhat: {
                gasPrice: 0,
                initialBaseFeePerGas: 0
            }
        }
    };

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hardhat-cfg-metamask
data:
  hardhat.config.js: |
    /** @type import('hardhat/config').HardhatUserConfig */
    module.exports = {
      solidity: "0.8.29",
      networks: {
        hardhat: {
          gasPrice: 0,
          initialBaseFeePerGas: 0,
          accounts: {
            mnemonic: process.env.SEED_PHRASE,
          },
          chainId: 1337,
        },
      },
    };

---
apiVersion: v1
kind: Pod
metadata:
  name: hardhat-node
  labels:
    app: hardhat
spec:
  containers:
    - name: hardhat
      image: gabilb/hardhat-node:v0.0.1
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 8545
          name: hardhat
          protocol: TCP
      volumeMounts:
        - name: hardhat-cfg
          mountPath: /hardhat/hardhat.config.js
          subPath: hardhat.config.js
      env:
        - name: SEED_PHRASE
          valueFrom:
            secretKeyRef:
              name: metamask-secret
              key: SEED_PHRASE
              optional: true
  volumes:
    - name: hardhat-cfg
      configMap:
        name: hardhat-cfg-basic

---
apiVersion: v1
kind: Service
metadata:
  name: hardhat-node
  labels:
    app: hardhat
spec:
  type: NodePort
  ports:
    - name: hardhat
      port: 8545
      targetPort: hardhat
      protocol: TCP
  selector:
    app: hardhat
